name: TheBareEssentials
version: '${project.version}'
main: be.thatsatim.thebareessentials.TheBareEssentials
api-version: 1.20
commands:
  fly:
    description: Toggle a player's ability to fly.
    usage: /fly [player]
    permission: TBE.fly
  top:
    description: Teleport to the highest block at your location.
    usage: /top [player]
    permission: TBE.top
  repair:
    description: repairs an item or the whole inventory of a player.
    usage: /repair <all / HeldItem> [playername]
    permission: TBE.repair