name: TheBareEssentials
version: '${project.version}'
main: be.thatsatim.thebareessentials.TheBareEssentials
api-version: 1.20
commands:
  fly:
    description: Toggle a player's ability to fly.
    usage: /fly [player]
    permission: TBE.fly
  top:
    description: Teleport to the highest block at your location.
    usage: /top [player]
    permission: TBE.top
  repair:
    description: repairs an item or the whole inventory of a player.
    usage: /repair <all / HeldItem> [playername]
    permission: TBE.repair
  gamemode:
    description: Set a players gamemode.
    usage: /gamemode <creative / survival / adventure / spectator> [playername]
    permission: TBE.gamemode
  gmc:
    description: Set a players gamemode to creative.
    usage: /gmc [playername]
    permission: TBE.gamemode
  gms:
    description: Set a players gamemode to survival.
    usage: /gms [playername]
    permission: TBE.gamemode
  gma:
    description: Set a players gamemode to adventure.
    usage: /gma [playername]
    permission: TBE.gamemode
  gmsp:
    description: Set a players gamemode to spectator.
    usage: /gmsp [playername]
    permission: TBE.gamemode